// static/src/components/ui/button/Button.vue
<script setup lang="ts">
import type { PrimitiveProps } from "radix-vue";
import type { HTMLAttributes } from "vue";
import type { ButtonVariants } from ".";
import { cn } from "$src/utils";
import { Primitive } from "radix-vue";
import { buttonVariants } from ".";

interface Props extends PrimitiveProps {
  variant?: ButtonVariants["variant"];
  size?: ButtonVariants["size"];
  class?: HTMLAttributes["class"];
}

const props = withDefaults(defineProps<Props>(), {
  as: "button",
});
</script>

<template>
  <Primitive :as="as" :as-child="asChild" :class="cn(buttonVariants({ variant, size }), props.class)">
    <slot />
  </Primitive>
</template>

// static/src/lib/components/ui/button/button.svelte
<script lang="ts">
  import { cn } from "$lib/utils.js";
  import { Button as ButtonPrimitive } from "bits-ui";
  import { buttonVariants, type Events, type Props } from "./index.js";

  type $$Props = Props;
  type $$Events = Events;

  let className: $$Props["class"];
  export let variant: $$Props["variant"] = "default";
  export let size: $$Props["size"] = "default";
  export let builders: $$Props["builders"] = [];
  export { className as class };
</script>

<ButtonPrimitive.Root
  {builders}
  class={cn(buttonVariants({ variant, size, className }))}
  type="button"
  {...$$restProps}
  on:click
  on:keydown
>
  <slot />
</ButtonPrimitive.Root>
